# Generated by Django 5.2.7 on 2026-05-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_logged_in_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Utilisé pour détecter si la session est toujours active via le heartbeat.', null=True, verbose_name='Dernière activité'),
        ),
    ]
