# Generated by Django 6.0.4 on 2026-04-26 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_cloture', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichierJustificatif', models.FileField(upload_to='justificatifs/')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
            },
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomType', models.CharField(max_length=100)),
                ('est_exceptionnel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congés',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nomEmpl', models.CharField(max_length=100)),
                ('prenomEmpl', models.CharField(max_length=100)),
                ('numTel', models.CharField(blank=True, max_length=20, null=True)),
                ('dateRecrutement', models.DateField()),
                ('categorie', models.CharField(choices=[('sol', 'Personnel au Sol (30j)'), ('navigant', 'Personnel Navigant (45j)'), ('sud', 'Personnel au Sud (45j)')], default='sol', help_text='Détermine le quota de congés annuel (30j ou 45j)', max_length=20)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='conges.fonction', verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDemande', models.DateField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree', models.FloatField(editable=False)),
                ('statut', models.CharField(choices=[('en_attente_resp', 'En attente Responsable'), ('en_attente_rh', 'En attente RH'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente_resp', max_length=20)),
                ('motif', models.CharField(blank=True, choices=[('mariage_perso', 'Mariage personnel (5j)'), ('naissance', 'Naissance (3j)'), ('deces_enfant', "Décès d'un enfant (5j)"), ('deces_proche', "Décès d'un proche (3j)"), ('mariage_enfant', "Mariage d'un enfant (3j)"), ('autre', 'Autre')], max_length=30, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='conges.employe')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='conges.exercice')),
                ('justificatif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conges.justificatif')),
                ('type_conge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='conges.typeconge')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-dateDemande'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateNotif', models.DateField(auto_now_add=True)),
                ('heureNotif', models.TimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-dateNotif', '-heureNotif'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_structures', to='conges.structure')),
                ('responsable', models.OneToOneField(blank=True, help_text='Le chef / responsable de cette structure', limit_choices_to={'compte__role__in': ['responsable_hierarchique', 'responsable_rh', 'directeur_rh']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_dirigee', to='conges.employe')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='conges.structure', verbose_name='Structure'),
        ),
        migrations.CreateModel(
            name='TitreConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('dureeT', models.FloatField()),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conges.demandeconge')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='conges.employe')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conges.exercice')),
            ],
            options={
                'verbose_name': 'Titre de congé',
                'verbose_name_plural': 'Titres de congé',
            },
        ),
        migrations.CreateModel(
            name='DroitConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrJCumule', models.FloatField(default=0, help_text='Reliquats des exercices précédents')),
                ('nbrJConsome', models.FloatField(default=0, help_text='Jours pris cette année')),
                ('nbrJRes', models.FloatField(default=0, help_text='Solde restant')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits_conges', to='conges.employe')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits_globaux', to='conges.exercice')),
            ],
            options={
                'verbose_name': 'Droit au congé',
                'verbose_name_plural': 'Droits aux congés',
                'unique_together': {('employe', 'exercice')},
            },
        ),
    ]
