# Generated by Django 6.0.3 on 2026-04-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True)),
                ('jours_conges_restants', models.FloatField(default=30)),
                ('date_embauche', models.DateField()),
                ('service', models.CharField(blank=True, max_length=100)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='conges.employe', verbose_name='Responsable direct')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('annuel', 'Congé annuel'), ('exceptionnel', 'Congé exceptionnel')], default='annuel', max_length=20)),
                ('motif', models.CharField(blank=True, choices=[('mariage', 'Mariage'), ('naissance', 'Naissance'), ('deces', 'Décès'), ('maladie', 'Maladie'), ('autres', 'Autres')], max_length=20, null=True)),
                ('raison', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente_responsable', 'En attente validation responsable'), ('validee_responsable', 'Validée par responsable'), ('en_attente_rh', 'En attente validation RH'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente_responsable', max_length=30)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation_responsable', models.DateTimeField(blank=True, null=True)),
                ('date_validation_rh', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='conges.employe')),
                ('responsable_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_responsable', to='conges.employe')),
                ('rh_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_rh', to='conges.employe')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conges.employe')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
