# Generated by Django 6.0.3 on 2026-04-18 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='conges.exercice'),
        ),
    ]
