# Generated by Django 6.0.4 on 2026-05-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/'),
        ),
        migrations.AddField(
            model_name='structure',
            name='est_structure_rh',
            field=models.BooleanField(default=False, help_text="Cochez cette case pour indiquer que c'est le département des Ressources Humaines. Seuls les membres d'une structure RH peuvent avoir le rôle RH."),
        ),
        migrations.DeleteModel(
            name='Justificatif',
        ),
    ]
