# Generated by Django 6.0.4 on 2026-04-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/'),
        ),
        migrations.DeleteModel(
            name='Justificatif',
        ),
    ]
