# Generated by Django 6.0.4 on 2026-04-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Le chef / responsable de cette structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_dirigees', to='conges.employe'),
        ),
    ]
