# Generated by Django 6.0.3 on 2026-04-26 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_alter_demandeconge_justificatif_delete_justificatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='est_structure_rh',
            field=models.BooleanField(default=False, help_text="Cochez cette case pour indiquer que c'est le département des Ressources Humaines. Seuls les membres d'une structure RH peuvent avoir le rôle RH."),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='conges.fonction', verbose_name='Fonction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='conges.structure', verbose_name='Structure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structure',
            name='responsable',
            field=models.OneToOneField(blank=True, help_text='Le chef / responsable de cette structure', limit_choices_to={'compte__role__in': ['responsable_hierarchique', 'responsable_rh', 'directeur_rh']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_dirigee', to='conges.employe'),
        ),
    ]
