# Generated by Django 6.0.3 on 2026-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_add_expiree_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('est_fixe', models.BooleanField(default=True, help_text='Si vrai, revient chaque année à la même date (ex: 1er Mai)')),
            ],
            options={
                'verbose_name': 'Jour Férié',
                'verbose_name_plural': 'Jours Fériés',
                'ordering': ['date'],
            },
        ),
    ]
