# Generated by Django 6.0.3 on 2026-05-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_jourferie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitreConge',
        ),
    ]
