# Generated by Django 6.0.3 on 2026-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('responsable_hierarchique', 'Responsable Hiérarchique'), ('responsable_rh', 'Responsable RH')], default='employe', max_length=30),
        ),
    ]
